In [1]:
import numpy as np

In [34]:
a = np.array([range(4),range(10,14)])

In [35]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [16]:
a[a>1]

array([ 2,  3, 10, 11, 12, 13])

In [17]:
a[np.logical_and(a>3, a<11)]

array([10])

In [30]:
b = np.array(range(6))

In [31]:
b

array([0, 1, 2, 3, 4, 5])

In [36]:
b.put([0],6)

In [37]:
b

array([6, 1, 2, 3, 4, 5])

In [38]:
c = np.array(range(5))

In [39]:
c

array([0, 1, 2, 3, 4])

In [40]:
b.put([0],c[-1])

In [41]:
b

array([4, 1, 2, 3, 4, 5])

In [42]:
a = np.array([2,-1,1,0])

In [43]:
b = np.array([0,3,2,1])

In [44]:
np.dot(a,b)

-1

In [45]:
c = np.array([range(3),range(10,13),[1,2,1]])

In [46]:
c

array([[ 0,  1,  2],
       [10, 11, 12],
       [ 1,  2,  1]])

In [48]:
t = np.linalg.inv(c)

In [50]:
np.dot(c,t)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.88178420e-16, 1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.38777878e-17, 1.00000000e+00]])

In [51]:
np.roots([1,2,10,18,9])

array([ 9.43689571e-16+3.00000000e+00j,  9.43689571e-16-3.00000000e+00j,
       -1.00000000e+00+1.51201539e-08j, -1.00000000e+00-1.51201539e-08j])

In [52]:
np.poly([1,-1,3,-3])

array([  1.,   0., -10.,   0.,   9.])

In [53]:
np.polyval([3,5,-16,-12],2)

0

In [66]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

In [67]:
len(x)

10

In [56]:
y = np.array([2,5,6,8,9,11,13,15,17,19])

In [65]:
len(y)

10

In [72]:
np.polyfit(x,y,2)

array([0.02272727, 1.56212121, 1.03333333])

In [73]:
a = np.array([range(4),range(10,14)])

In [74]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [76]:
np.median(a)

6.5

In [77]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [78]:
np.random.rand(2,4)

array([[0.20504893, 0.7265295 , 0.96019195, 0.47263035],
       [0.92962999, 0.49695065, 0.81755287, 0.86506757]])

In [79]:
np.random.randint(2,10)

5

In [80]:
b = np.random.normal(size=40)

In [81]:
b

array([ 0.38214101, -1.47566182,  0.7707012 ,  2.68619449, -0.05736613,
        0.32896732, -0.65259721, -1.0176122 ,  0.15777477,  0.02812178,
       -1.14649732,  0.53840019,  1.6865855 ,  1.27101798,  1.19940126,
       -1.51363578, -1.36046359, -0.65632343,  1.91628998,  0.59915439,
        0.57105378, -0.15354372,  0.30228295,  1.55441087, -0.3758351 ,
       -0.98799551, -2.19758564,  0.48064021,  1.96506887, -0.93180119,
        1.25868128,  1.93463144, -0.55532139,  0.60629785,  0.30241742,
       -1.08175149, -1.19639919,  0.55676238, -0.51331458, -0.88128103])

In [82]:
np.random.shuffle(b)

In [83]:
b

array([ 1.93463144, -0.51331458,  1.96506887, -1.51363578,  0.60629785,
        0.57105378,  1.27101798,  1.19940126, -0.88128103,  0.30241742,
        2.68619449,  1.55441087, -2.19758564,  0.15777477,  0.30228295,
       -1.36046359,  1.6865855 , -1.14649732, -0.3758351 ,  0.59915439,
       -1.47566182,  1.25868128,  0.32896732, -0.93180119,  0.02812178,
        0.7707012 , -1.19639919, -0.65632343, -0.65259721,  1.91628998,
       -0.55532139,  0.55676238, -0.98799551,  0.38214101,  0.48064021,
       -1.0176122 , -0.15354372, -0.05736613, -1.08175149,  0.53840019])

In [85]:
#Quiz2

In [86]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [88]:
b

array([ 1.93463144, -0.51331458,  1.96506887, -1.51363578,  0.60629785,
        0.57105378,  1.27101798,  1.19940126, -0.88128103,  0.30241742,
        2.68619449,  1.55441087, -2.19758564,  0.15777477,  0.30228295,
       -1.36046359,  1.6865855 , -1.14649732, -0.3758351 ,  0.59915439,
       -1.47566182,  1.25868128,  0.32896732, -0.93180119,  0.02812178,
        0.7707012 , -1.19639919, -0.65632343, -0.65259721,  1.91628998,
       -0.55532139,  0.55676238, -0.98799551,  0.38214101,  0.48064021,
       -1.0176122 , -0.15354372, -0.05736613, -1.08175149,  0.53840019])

In [96]:
a = b.copy()

In [97]:
a

array([ 1.93463144, -0.51331458,  1.96506887, -1.51363578,  0.60629785,
        0.57105378,  1.27101798,  1.19940126, -0.88128103,  0.30241742,
        2.68619449,  1.55441087, -2.19758564,  0.15777477,  0.30228295,
       -1.36046359,  1.6865855 , -1.14649732, -0.3758351 ,  0.59915439,
       -1.47566182,  1.25868128,  0.32896732, -0.93180119,  0.02812178,
        0.7707012 , -1.19639919, -0.65632343, -0.65259721,  1.91628998,
       -0.55532139,  0.55676238, -0.98799551,  0.38214101,  0.48064021,
       -1.0176122 , -0.15354372, -0.05736613, -1.08175149,  0.53840019])

In [102]:
a = np.array([[1,2,3],[4,5,6]])

In [103]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
a.reshape(2,2)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [104]:
np.resize(a,(2,2))

array([[1, 2],
       [3, 4]])

In [105]:
vec=np.array([1,2,3,4,5])

In [106]:
vec<4

array([ True,  True,  True, False, False])

In [107]:
vec[vec<4]

array([1, 2, 3])

In [108]:
A=np.array([1,2,3,4,5,6,7,8])

In [109]:
Conditions = [A<4,A>6]

In [110]:
Choice=[A+1,A-1]

In [111]:
np.select(Conditions, Choice)

array([2, 3, 4, 0, 0, 0, 6, 7])

In [112]:
A=np.array([1,2,3,4,5,6,7,8])

In [113]:
np.where(A<=6,A+2,7)

array([3, 4, 5, 6, 7, 8, 7, 7])